import { WeaponData } from '../types/game';

export const WEAPONS_DATABASE: Record<string, WeaponData> = {
  fist: {
    id: 'fist',
    name: 'Fist',
    type: 'melee',
    damage: 18,
    fireRate: 2.8,
    range: 75,
    magazineSize: Infinity,
    reloadTime: 0,
    knockback: 200,
    color: '#e2e8f0',
    description: 'Quick close-quarters combo strikes with rapid recovery.',
    iconType: 'fist',
  },
  sword: {
    id: 'sword',
    name: 'Katana Blade',
    type: 'melee',
    damage: 46,
    fireRate: 1.8,
    range: 100,
    magazineSize: Infinity,
    reloadTime: 0,
    knockback: 280,
    color: '#38bdf8',
    description: 'Sweeping razor-sharp slashes cutting through multiple targets.',
    iconType: 'sword',
  },
  bat: {
    id: 'bat',
    name: 'Heavy Baseball Bat',
    type: 'melee',
    damage: 68,
    fireRate: 1.2,
    range: 95,
    magazineSize: Infinity,
    reloadTime: 0,
    knockback: 480,
    color: '#fbbf24',
    description: 'Devastating blunt force impact delivering massive knockback.',
    iconType: 'bat',
  },
  pistol: {
    id: 'pistol',
    name: 'Tactical Pistol',
    type: 'ranged',
    damage: 24,
    fireRate: 3.5,
    range: 650,
    magazineSize: 12,
    reloadTime: 1.2,
    knockback: 120,
    projectileSpeed: 950,
    spread: 0.04,
    color: '#a855f7',
    description: 'Reliable sidearm offering high accuracy and swift reloads.',
    iconType: 'pistol',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Pump Shotgun',
    type: 'ranged',
    damage: 16, // per pellet
    fireRate: 1.1,
    range: 420,
    magazineSize: 6,
    reloadTime: 2.1,
    knockback: 320,
    projectileSpeed: 820,
    spread: 0.26,
    pellets: 6,
    color: '#ef4444',
    description: 'Fires heavy buckshot spread for devastating lethal point-blank damage.',
    iconType: 'shotgun',
  },
  rifle: {
    id: 'rifle',
    name: 'Assault Rifle AR-15',
    type: 'ranged',
    damage: 19,
    fireRate: 8.5,
    range: 720,
    magazineSize: 30,
    reloadTime: 1.8,
    knockback: 90,
    projectileSpeed: 1050,
    spread: 0.08,
    color: '#10b981',
    description: 'High-rate automatic fire suppressing enemy waves from distance.',
    iconType: 'rifle',
  },
  grenade: {
    id: 'grenade',
    name: 'Frag Grenade',
    type: 'special',
    damage: 130,
    fireRate: 0.9,
    range: 500,
    magazineSize: 4,
    reloadTime: 2.5,
    knockback: 650,
    projectileSpeed: 520,
    color: '#f97316',
    description: 'Bouncing explosive ordinance clearing rooms with immense blast radius.',
    iconType: 'grenade',
  },
};

export const ALL_WEAPON_IDS = Object.keys(WEAPONS_DATABASE);

export function getWeaponData(id: string): WeaponData {
  return WEAPONS_DATABASE[id] || WEAPONS_DATABASE.fist;
}
